config/routes.rb
DoorMat::Engine.routes.draw do
  get '/sign_up' => 'sign_up#new', as: 'sign_up'
  post '/sign_up' => 'sign_up#create'

  get '/sign_in' => 'sign_in#new', as: 'sign_in'
  post '/sign_in' => 'sign_in#create'
  get '/sign_out' => 'sign_in#destroy', as: 'sign_out'

  post '/terminate_session/:guid' => 'sessions#terminate', as: 'terminate_session'
  get '/reconfirm_password' => 'reconfirm_password#new', as: 'reconfirm_password'
  post '/reconfirm_password' => 'reconfirm_password#create'

  get '/add_email' => 'manage_email#new', as: 'add_email'
  post '/add_email' => 'manage_email#create'
  post '/delete_email' => 'manage_email#destroy'
  post '/set_primary_email' => 'manage_email#set_primary_email'

  get '/email_confirmation_required' => 'static#email_confirmation_required', as: 'email_confirmation_required'
  get '/confirm_email/:token/:email' => 'activities#confirm_email', as: 'confirm_email'
  post '/resend_email_confirmation' => 'activities#resend_email_confirmation', as: 'resend_email_confirmation'
  post '/download_recovery_key' => 'activities#download_recovery_key', as: 'download_recovery_key'

  get '/change_password' => 'change_password#new', as: 'change_password'
  post '/change_password' => 'change_password#create'

  get '/forgot_password_verification_mail_sent' => 'static#forgot_password_verification_mail_sent'

  get '/forgot_password' => 'forgot_passwords#new'
  post '/forgot_password' => 'forgot_passwords#create'
  get '/choose_new_password/:token/:email' => 'forgot_passwords#choose_new_password', as: 'choose_new_password'
  post '/reset_password' => 'forgot_passwords#reset_password', as: 'reset_password'
end

Rails.application.routes.draw do

  root 'static#home'
  get '/about' => 'static#about'

  get '/passwords' => 'passwords#index', as: 'passwords'
  post '/passwords' => 'passwords#create'
  get '/passwords/new' => 'passwords#new', as: 'new_password'
  get '/passwords/:id' => 'passwords#show', as: 'password'
  delete '/passwords/:id' => 'passwords#destroy'

  mount DoorMat::Engine => "/", as: "door_mat"

  match '*path', via: :all, to: 'static#home'

end

app/models/password.rb
class Password < ActiveRecord::Base
  include DoorMat::AttrSymmetricStore

  belongs_to :actor, class_name: 'DoorMat::Actor'

  attr_symmetric_store :subject, :password

  after_find do |record|
    record.length = record.password.length
  end

  validates :subject, presence: true
  validates :subject, length: { maximum: 50 }
  validates :length, numericality: { only_integer: true, greater_than_or_equal_to: 8, less_than_or_equal_to: 64 }

  attr_accessor :length, :capital, :numeric, :special

  def self.new_w_default
    p = self.new
    p.length = 20
    p.capital = p.numeric = p.special = '1'
    p
  end

  def generate
    valid_characters = [*('a'..'z')]
    valid_characters += [*('A'..'Z')]  if '1' == @capital
    valid_characters += [*(0..9)] if '1' == @numeric
    valid_characters += ['!', '#', '$', '%', '&', '*', '+', ',', '-', '.',
                         '/', ':', ';', '<', '=', '>', '?', '@', '^', '_'] if '1' == @special

    password = []
    @length.to_i.times { password << valid_characters[SecureRandom.random_number(valid_characters.count)] }
    self.password = password.join()
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  include DoorMat::Controller
  before_action :require_valid_session
  before_action :require_confirmed_email
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController

  def index
    @actor = DoorMat::Session.current_session.actor
    @passwords = @actor.passwords.order(:subject, :created_at)
  end

  def show
    @password = DoorMat::Session.current_session.actor.passwords.find(params[:id].to_i)
  rescue ActiveRecord::RecordNotFound
    flash[:notice] = 'Record not found - The password you requested could not be found'
    redirect_to passwords_url
  end

  def new
    @password = Password.new_w_default
  end

  # no edit

  def create
    @password = DoorMat::Session.current_session.actor.passwords.build(password_params)
    if @password.valid? && @password.generate && @password.save
      flash[:notice] = 'New password created'
      redirect_to password_path(@password)
    else
      render :new
    end
  end

  # no update

  def destroy
    @password = DoorMat::Session.current_session.actor.passwords.find(params[:id].to_i)
    @password.destroy
    flash[:notice] = 'Password was deleted'

  rescue ActiveRecord::RecordNotFound
    flash[:notice] = 'Record not found - The password you requested could not be found'
  ensure
    redirect_to passwords_url
  end

  private
  def password_params
    params.require(:password).permit(:subject, :length, :capital, :numeric, :special)
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  skip_before_action :require_valid_session, only: [:about, :home]
  skip_before_action :require_confirmed_email, only: [:about, :home]

  # A valid session is not required in the static pages but if present
  # the application layout will display the user email address and
  # Sign Out button.
  before_action -> { DoorMat::Session.from(cookies, request) }
end

app/helpers/application_helper.rb
module ApplicationHelper

  # https://gist.github.com/roberto/3344628
  def bootstrap_class_for(flash_type)
    {
        :success => 'alert-success',
        :error => 'alert-danger',
        :danger => 'alert-danger',
        :alert => 'alert-warning',
        :warning => 'alert-warning',
        :warn => 'alert-warning',
        :notice => 'alert-info',
        :info => 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def session_type(session)
    {
        :public_computer => 'Public Computer',
        :private_computer => 'Private Computer',
        :remember_me => 'Private Computer / Remember Me'
    }[session.rating.to_sym]
  end

end

app/views/door_mat/change_password/new.html.erb
<ol class="breadcrumb">
  <li><%= link_to('Back to Passwords', main_app.passwords_path, :style => 'color:#000000;') %></li>
  <li class="active">Change Account Password</li>
</ol>

<div class="row">
  <div class="col-md-offset-4 col-md-4">
    <div class="panel panel-default text-center">
      <div class="panel-body">

        <%= form_for(@change_password, url: change_password_path) do |f| %>
            <%= render 'door_mat/helpers/errors_if_any', {object: @change_password} %>

            <div class="field">
              <%= f.label :old_password %><br>
              <%= f.password_field :old_password %>
            </div>
            <div class="field">
              <%= f.label :new_password %><br>
              <%= f.password_field :new_password %>
            </div>
            <div class="field">
              <%= f.label :new_password_confirmation %><br>
              <%= f.password_field :new_password_confirmation %>
            </div>

            <div class="actions" style="margin-top: 15px">
              <%= f.submit t("door_mat.change_password.submit_button"), {class: "btn btn-default btn-sm text-center", role: "button"} %>
            </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/door_mat/forgot_passwords/choose_new_password.html.erb
<div class="row">
  <div class="col-md-offset-4 col-md-4">
    <div class="panel panel-default text-center">
      <div class="panel-body">
        <h1>Forgot Password</h1>


        <%= form_for(@forgot_password, url: reset_password_path) do |f| %>
            <%= render 'door_mat/helpers/errors_if_any', {object: @forgot_password} %>

            <div class="field">
              <%= f.hidden_field :token %>
            </div>

            <div class="field">
              <%= f.label :email %><br>
              <%= f.text_field :email %>
            </div>

            <div class="field">
              <%= f.label :password %><br>
              <%= f.password_field :password %>
            </div>

            <div class="field">
              <%= f.label :password_confirmation %><br>
              <%= f.password_field :password_confirmation %>
            </div>

            <div class="field", style="margin-top: 15px">
              <%= f.label :recovery_key %><br>
              <%= f.file_field :recovery_key %>
            </div>

            <div class="actions", style="margin-top: 15px">
              <%= f.submit t("door_mat.forgot_password.submit_button"), {class: "btn btn-default btn-lg", role: "button"} %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/door_mat/forgot_passwords/new.html.erb
<div class="row">
  <div class="col-md-offset-4 col-md-4">
    <div class="panel panel-default text-center">
      <div class="panel-body">
        <h1>Forgot Your Password?</h1>

        <%= form_for(@forgot_password, url: forgot_password_path) do |f| %>
            <%= render 'door_mat/helpers/errors_if_any', {object: @forgot_password} %>

            <div class="field">
              <%= f.label :email %><br>
              <%= f.text_field :email %>
            </div>

            <div class="actions", style="margin-top: 15px">
              <%= f.submit t("door_mat.forgot_password.submit_button"), {class: "btn btn-default btn-lg", role: "button"} %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/door_mat/manage_email/new.html.erb
<ol class="breadcrumb">
  <li><%= link_to('Back to Passwords', main_app.passwords_path, :style => 'color:#000000;') %></li>
  <li class="active">Add email</li>
</ol>

<div class="row">
  <div class="col-md-offset-4 col-md-4">
    <div class="panel panel-default text-center">
      <div class="panel-body">

        <%= form_for(@email, url: add_email_path) do |f| %>
            <%= render 'door_mat/helpers/errors_if_any', {object: @email} %>

            <div class="field">
              <%= f.label :address %><br>
              <%= f.text_field :address %>
            </div>

            <div class="actions" style="margin-top: 15px">
              <%= f.submit t("door_mat.manage_email.add_button"), {class: "btn btn-default btn-sm text-center", role: "button"} %>
            </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/door_mat/reconfirm_password/new.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <div class="panel panel-default text-center">
      <div class="panel-body">

        <h1>Reconfirm Password</h1>

        <% if @current_session_email.blank? %>
            <p>Please type in your password one more time:</p>
        <% else %>
            <p>Please type in the <%= @current_session_email %> password one more time:</p>
        <% end %>

        <%= form_tag(door_mat.reconfirm_password_path) do %>
            <%= password_field_tag %>
            <%= submit_tag("Reconfirm", {class: "btn btn-default btn-sm text-center", role: "button", style: "margin: 15px"}) %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/door_mat/sign_in/new.html.erb
<div class="row">
  <div class="col-md-offset-4 col-md-4">
  <div class="panel panel-default text-center">
    <div class="panel-body">
      <h1>Sign In</h1>

      <%= form_for(@sign_in, url: sign_in_path) do |f| %>
          <%= render 'door_mat/helpers/errors_if_any', {object: @sign_in} %>

          <div class="field">
            <%= f.label :email %><br>
            <%= f.text_field :email %>
          </div>
          <div class="field">
            <%= f.label :password %><br>
            <%= f.password_field :password %>
          </div>
          <div class="field">
            <%= f.label :is_this_a_public_computer? %>
            <%= f.check_box :is_public %>
          </div>
          <div class="field">
            <%= f.label :remember_me? %>
            <%= f.check_box :remember_me %>
          </div>
          <p><%= link_to t("door_mat.forgot_password.link"), forgot_password_path %></p>

          <div class="actions", style="margin-top: 15px">
            <%= f.submit t("door_mat.sign_in.submit_button"), {class: "btn btn-default btn-lg", role: "button"} %>
          </div>
      <% end %>


      <p>Don't have an account yet? <%= link_to 'Sign Up', sign_up_path %></p>
    </div>
  </div>
  </div>
</div>

app/views/door_mat/sign_up/new.html.erb
<div class="row">
  <div class="col-md-offset-4 col-md-4">
    <div class="panel panel-default text-center">
      <div class="panel-body">
        <h1>Sign Up</h1>

        <%= form_for(@sign_up, url: sign_up_path) do |f| %>
            <%= render 'door_mat/helpers/errors_if_any', {object: @sign_up} %>

            <div class="field">
              <%= f.label :email %><br>
              <%= f.text_field :email %>
            </div>
            <div class="field">
              <%= f.label :password %><br>
              <%= f.password_field :password %>
            </div>
            <div class="field">
              <%= f.label :password_confirmation %><br>
              <%= f.password_field :password_confirmation %>
            </div>

            <div class="actions", style="margin-top: 15px">
              <%= f.submit t("door_mat.sign_up.submit_button"), {class: "btn btn-default btn-lg", role: "button"} %>
            </div>
        <% end %>

        <p>Already have an account? <%= link_to 'Sign In', sign_in_path %></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>&mu;PM</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="row">
  <div class="col-sm-offset-4 col-sm-4">
    <h1 class="text-center">
      <%= link_to '&mu;PM'.html_safe, main_app.root_path, :style => 'color:#000000;' %>
    </h1>
  </div>
  <div class="col-sm-4">
    <% if DoorMat::Session.current_session.valid? %>
        <h5 class="text-center"><%= DoorMat::Session.current_session.email.address %> -
          <%= link_to 'Sign Out', door_mat.sign_out_path, {class: "btn btn-default btn-lg", role: "button"} %></h5>

    <% end %>
  </div>
</div>

<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> fade in text-center">
      <%= message %>
    </div>
<% end %>

<div class="container-fluid" style="margin-top: 55px">
  <%= yield %>
</div>

<footer class="footer">
  <div class="container">
    <div class="row text-center" style="padding: 20px;">
      <nav class="col-sm-6">
        &mu;PM &trade; is a trademark of <a href="http://datamolecule.com">Data Molecule Inc.</a> &copy; 2016.
      </nav>
      <nav class="col-sm-6"><%= link_to 'About &mu;PM'.html_safe, main_app.about_path %></nav>
    </div>
  </div>
</footer>
</div>

</body>
</html>